---
http_interactions:
- request:
    method: post
    uri: https://accounts.google.com/o/oauth2/token
    body:
      encoding: US-ASCII
      string: client_id=____SILENCED:_client_id____&client_secret=____SILENCED:_client_secret____&grant_type=refresh_token&refresh_token=____SILENCED:_refresh_token____
    headers:
      host:
      - accounts.google.com
      date:
      - Tue, 30 Oct 2012 04:44:05 GMT
      content-type:
      - application/x-www-form-urlencoded
      content-length:
      - '0'
      accept:
      - ! '*/*'
      user-agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      cache-control:
      - no-cache, no-store, max-age=0, must-revalidate
      pragma:
      - no-cache
      expires:
      - Fri, 01 Jan 1990 00:00:00 GMT
      date:
      - Tue, 30 Oct 2012 04:44:06 GMT
      content-type:
      - application/json
      x-content-type-options:
      - nosniff
      x-frame-options:
      - SAMEORIGIN
      x-xss-protection:
      - 1; mode=block
      server:
      - GSE
      connection:
      - close
    body:
      encoding: US-ASCII
      string: ! "{\n  \"access_token\" : \"ya29.AHES6ZRJ_VNNzeZCM8EUICn8xLlPn2e_LUs2Fs7staD2rNxmxlt5Aqc\",\n
        \ \"token_type\" : \"Bearer\",\n  \"expires_in\" : 3600\n}"
    http_version: '1.1'
  recorded_at: Tue, 30 Oct 2012 04:44:06 GMT
recorded_with: VCR 2.2.5
