---
http_interactions:
- request:
    method: post
    uri: https://accounts.google.com/o/oauth2/token
    body:
      encoding: US-ASCII
      string: client_id=____SILENCED_client_id____&client_secret=____SILENCED_client_secret____&grant_type=refresh_token&refresh_token=____SILENCED_refresh_token____
    headers:
      host:
      - accounts.google.com
      date:
      - Wed, 31 Oct 2012 00:26:02 GMT
      content-type:
      - application/x-www-form-urlencoded
      content-length:
      - '0'
      accept:
      - ! '*/*'
      user-agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      cache-control:
      - no-cache, no-store, max-age=0, must-revalidate
      pragma:
      - no-cache
      expires:
      - Fri, 01 Jan 1990 00:00:00 GMT
      date:
      - Wed, 31 Oct 2012 00:26:02 GMT
      content-type:
      - application/json
      x-content-type-options:
      - nosniff
      x-frame-options:
      - SAMEORIGIN
      x-xss-protection:
      - 1; mode=block
      server:
      - GSE
      connection:
      - close
    body:
      encoding: US-ASCII
      string: ! "{\n  \"access_token\" : \"____SILENCED_access_token____\",\n  \"token_type\"
        : \"Bearer\",\n  \"expires_in\" : 3600\n}"
    http_version: '1.1'
  recorded_at: Wed, 31 Oct 2012 00:26:02 GMT
- request:
    method: put
    uri: https://7baa01c0-04f5-0130-7987-0023dfa5d78c.commondatastorage.googleapis.com/?websiteConfig
    body:
      encoding: US-ASCII
      string: <WebsiteConfiguration></WebsiteConfiguration>
    headers:
      accept:
      - ! '*/*'
      user-agent:
      - Ruby
      host:
      - 7baa01c0-04f5-0130-7987-0023dfa5d78c.commondatastorage.googleapis.com
      date:
      - Wed, 31 Oct 2012 00:26:02 GMT
      content-type:
      - binary/octet-stream
      content-length:
      - '45'
      x-goog-api-version:
      - 2
      authorization:
      - Bearer ____SILENCED_access_token____
  response:
    status:
      code: 200
      message: OK
    headers:
      server:
      - HTTP Upload Server Built on Oct 3 2012 16:52:30 (1349308350)
      vary:
      - Origin
      date:
      - Wed, 31 Oct 2012 00:26:03 GMT
      pragma:
      - no-cache
      expires:
      - Fri, 01 Jan 1990 00:00:00 GMT
      cache-control:
      - no-cache, no-store, must-revalidate
      content-length:
      - '0'
      content-type:
      - text/html; charset=UTF-8
    body:
      encoding: US-ASCII
      string: ''
    http_version: '1.1'
  recorded_at: Wed, 31 Oct 2012 00:26:03 GMT
recorded_with: VCR 2.3.0
